export function createAppState() {
  return {
    manifest: null,
    items: [],
    sources: [],
    kit: {
      items: [],
      itemByAsset: new Map(),
      secondaryPools: {},
      curveTables: {},
      characters: [],
      characterById: new Map(),
      characterSkins: [],
      skinById: new Map(),
      perks: [],
      perkById: new Map(),
    },
    kitReady: false,
    kitPromise: null,
    itemSearchIndex: new Map(),
    sourceSearchIndex: new Map(),
    kitSearchIndex: new Map(),
    builder: {
      characterId: "",
      selectedSlot: "weapon1Primary",
      activeWeaponSet: "1",
      search: "",
      rarity: "All",
      pickerOpen: false,
      pickerMode: "items",
      equipped: {},
      primaryValues: {},
      bonuses: {},
      perks: [],
      skinId: "",
      confirmAction: null,
      shareStatus: "",
    },
    damageTarget: {
      weaponSet: "1",
      hand: "primary",
      hitLocation: "torso",
      pdr: -22,
      mdr: -22,
      comboMultiplier: 0,
    },
    itemByAsset: new Map(),
    sourceByKey: new Map(),
    rateWeights: {},
    ratesPromise: null,
    favorites: { items: [], sources: [] },
    favoriteItemSet: new Set(),
    favoriteSourceSet: new Set(),
    savedKits: [],
    chipPopover: { target: null, pinned: false },
    slotTooltip: { target: null },
    activeTab: "items",
    visibleRows: { items: 160, sources: 160 },
    globalSearch: "",
    detailCache: new Map(),
    currentLuck: 0,
    activeDetail: null,
    sort: {
      items: { key: "item", direction: "asc" },
      sources: { key: "source", direction: "asc" },
    },
  };
}
